-- DROP the table if exists

CREATE TABLE agent (
    id INTEGER PRIMARY GENERATED BY DEFAULT AS IDENTITY,
    agent_name TEXT NOT NULL,
    license_num NUMERIC NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    license_exp DATE,
    brokerage TEXT,
    sponsor_date DATE,
    list_units DECIMAL (7,2) NOT NULL,
    list_vol DECIMAL (12,2) NOT NULL,
    sell_units DECIMAL (7,2) NOT NULL,
    sell_vol DECIMAL (12,2) NOT NULL,
    tot_units DECIMAL (10,2) NOT NULL,
    tot_vol DECIMAL (14,2) NOT NULL
);

CREATE TABLE brokerage (
    id INTEGER PRIMARY GENERATE BY DEFAULT AS IDENTITY,
    brokerage_name TEXT NOT NULL,
    broker_name TEXT NOT NULL,
    street TEXT,
    city TEXT,
    st TEXT
);

CREATE TABLE user (
    id INTEGER PRIMARY GENERATE BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    brokerage INTEGER NOT NULL
);

CREATE TABLE note (
    id INTEGER PRIMARY GENERATE BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    username_id INTEGER NOT NULL,
    agent_id INTEGER NOT NULL
);

CREATE TABLE followed_agents (
    agent_id INTEGER REFERENCES agent(id),
    username_id 
)