CREATE TABLE agents (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    agent_name TEXT NOT NULL,
    license_num NUMERIC NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    license_exp DATE,
    sponsor_date DATE,
    list_units INTEGER NOT NULL,
    list_vol DECIMAL (12,2) NOT NULL,
    sell_units INTEGER NOT NULL,
    sell_vol DECIMAL (12,2) NOT NULL,
    tot_units INTEGER NOT NULL,
    tot_vol DECIMAL (14,2) NOT NULL
);