CREATE TABLE brokerages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brokerage_name TEXT NOT NULL,
    broker_id INTEGER REFERENCES agents(id),
    street TEXT,
    city TEXT,
    st TEXT
);